apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: app
  template:
    metadata:
      labels: 
        app: app
    spec:          
      containers:
        - name: web
          image: 080598/django:stable
          imagePullPolicy: "IfNotPresent"
          command: ["/bin/sh","-c"]
          args:
          - python manage.py makemigrations;
            python manage.py migrate;
            python manage.py collectstatic --no-input;
            gunicorn mysite.wsgi:application --bind 0.0.0.0:8000;
          env:
          - name: DB_PASS
            value: root
          - name: DB_USER
            value: postgres
          - name: DB_NAME
            value: app
          - name: DB_HOST
            value: pgpool-svc
          ports:
            - name: app
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: app-volume
              mountPath: /mysite/static
        - name: nginx
          image: 080598/nginx
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: nginx
              containerPort: 80
              protocol: TCP
          volumeMounts:
              - name: app-volume
                mountPath: /home/app/web/staticfiles/
      volumes:
          
          - name: app-volume
            emptyDir: {}