apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: nginx
      port: 80
      targetPort: nginx
      protocol: TCP
      nodePort: null
  selector:
    app: app