version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./mysite:/mysite
      - static_volume:/mysite/static
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DEBUG=False
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=root
      - DB_PASS=root

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  
  nginx:
    build: ./nginx
    image: nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 1337:80
    depends_on:
      - app
      
  nginx-bortli:
    # image: fholzer/nginx-brotli
    image:  nginx-brotli
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./nginx-bortli/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-bortli/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 1338:80
    depends_on:
      - app

volumes:
  static_volume: