apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    upstream django {
      server 127.0.0.1:8000;
    }
    server {
      listen 80;

      location /static/ {
        alias /static/;
      }

      location / {
        proxy_pass http://django;
        proxy_set_header Host $host;
      }
    }