# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-05 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=560)),
            ],
        ),
        migrations.CreateModel(
            name='MusicRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=560)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RecordLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=560)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='music.RecordLabel'),
        ),
        migrations.AddField(
            model_name='artist',
            name='music_releases',
            field=models.ManyToManyField(related_name='artists', to='music.MusicRelease'),
        ),
    ]
