# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-05 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicrelease',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
