# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-05 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20220105_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='music_releases',
            field=models.ManyToManyField(null=True, related_name='artists', to='music.MusicRelease'),
        ),
    ]
